### PR TITLE
140 re draw figures

### LINKED ISSUE #140: Re-draw figures - add new classes and properties
See figure captions marked 'TODO'

### PR DESCRIPTION
**Pull request by dr-shorthair**
Re-draw figures with new properties and classes
Preview here: https://raw.githack.com/w3c/sdw-sosa-ssn/140-re-draw-figures/ssn/index.html

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Alongside the new diagrams I did the following parallel consistency checks: 
- Checked domain/rangeIncludes and diagram are consistent 
- Checked html and ttl skos:definitions are consistent

**Comment by dr-shorthair** [comment]
This PR is ready to go now - all diagrams have been re-drawn using consistent notation, which is described towards the top of the document. 
Diagrams are consistent with ontology. 

@oldskeptic @alexrobin @hylkevds could you take a look please?

**Review by maximelefrancois86 — APPROVED** [review]
Could you please add the sources of the diagrams (drawio file) somewhere ?

**Comment by dr-shorthair** [comment]
I'm using Lucid (OGC staff license) so the best I can do is SVG and a set of links to the Lucid documents - see /images/readme.md

**Review by rob-metalinkage — APPROVED** [review]

**Pull request merged**
