### PR TITLE
Mirror ssn resources in sosa

### LINKED ISSUE #48: Should we merge SSN and SOSA into a single namespace?
The idea would be to define all classes in SOSA, including Deployment, System, etc. that only exist in the SSN namespace as of today.

Even if we do that, we could keep the existing classes in the SSN namespace for backwards compatibility and just map them as equivalent to the new ones we add to SOSA namespace.

What do we do with constraints that are only defined in SSN in the current version?

### PR DESCRIPTION
**Pull request by dr-shorthair**
- All SSN classes and properties cloned into SOSA namespace and graph, following existing axiomatization and annotation rules applicable to each graph (file)
- `owl:equivalentClass` and `owl:equivalentProperty` axioms added to both sides, in SSN graph

Fixes #48

### CODE REVIEW

**Review by rob-metalinkage — COMMENTED** [review]
Looks good - but are we replicating stuff Alex Robin did ?

**Comment by dr-shorthair** [comment]
Did Alex create new classes/properties in the SSN namespace?

**Review by rob-metalinkage — APPROVED** [review]
Discussed in meeting 21/09/2023 - happy this consolidates @AlexRobins input ready for issue processing.

**Review by sgrellet — APPROVED** [review]
Aligned with discussion in meeting 21/09/2023

**Pull request merged**
