### PR TITLE
Moved Sample and Procedure specializations to SOSA

### LINKED ISSUE #132: Move extra OMS terms into SOSA core
A number of new terms are defined in the [SOSA-OMS graph](https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/integrated/sosa-oms.ttl) to implement terms from OMS that are not currently in the SOSA core graph. 

Should any of these be added to SOSA core? 

- [x] [sosa-oms:SpatialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSpatialSample)
- [x] [sosa-oms:MaterialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSMaterialSample)
- [x] [sosa-oms:StatisticalSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSStatisticalSample)
- [x] [sosa-oms:ObservingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSObservingProcedure)
- [x] [sosa-oms:SamplingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSamplingProcedure)
- [x] [sosa-oms:PreparationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSPreparationProcedure)
- [x] and for completeness [sosa-oms:ActuationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSActuationProcedure)
- [ ] [sosa-oms:PreparationStep](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSPreparationStep)
- [ ] [sosa-oms:hasPreparationStep](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMShasPreparationStep)
- [ ] [sosa-oms:madeOnPlatform](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSmadeOnPlatform)
- [ ] [sosa-oms:metadata](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSmetadata)
- [ ] [sosa-oms:observationType](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSobservationType)
- [ ] [sosa-oms:preparedSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSpreparedSample)
- [ ] [sosa-oms:processingDetails](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSprocessingDetails)
- [x] [sosa-oms:relatedObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSrelatedObservation)
- [ ] [sosa-oms:relatedSampling](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSrelatedSampling)
- [x] [sosa-oms:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSresultQuality)
- [ ] [sosa-oms:samplePreparationStep](https://w3c.github.io/sdw-sosa-s8n/ssn/#OMSsamplePreparationStep)
- [ ] [sosa-oms:validTime](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSvalidTime)

### PR DESCRIPTION
**Pull request by dr-shorthair**
Also move resultQuality and relatedObservation to SOSA

Closes #132

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Preview at 
https://raw.githack.com/w3c/sdw-sosa-ssn/132-move-extra-oms-terms-into-sosa-core/ssn/index.html#Sampling
https://raw.githack.com/w3c/sdw-sosa-ssn/132-move-extra-oms-terms-into-sosa-core/ssn/index.html#Procedures
https://raw.githack.com/w3c/sdw-sosa-ssn/132-move-extra-oms-terms-into-sosa-core/ssn/index.html#OMS-Alignment-Class
etc

**Comment by dr-shorthair** [comment]
This PR must be merged prior to the new modularization work suggested in https://github.com/w3c/sdw-sosa-ssn/issues/183#issuecomment-1913860023

**Comment by alexrobin** [comment]
I'm good with this PR overall, but I have two questions:

- Does it make sense to bring `PreparationProcedure` into `sosa` namespace if we are not bringing `PreparationStep`? 

- Should the range of `usedProcedure` on `Observation/Actuation/Sampling` be adjusted to allow only the specialized procedure classes?

**Comment by dr-shorthair** [comment]
> * Does it make sense to bring `PreparationProcedure` into `sosa` namespace if we are not bringing `PreparationStep`?
> * Should the range of `usedProcedure` on `Observation/Actuation/Sampling` be adjusted to allow only the specialized procedure classes?

Thanks @alexrobin - fixed these. 
Can you now approve merge? 

@hylkevds @sgrellet @KathiSchleidt can you approve please?

**Review by alexrobin — APPROVED** [review]
I'm approving this but I noticed that the HTML documentation still refers to `sosa:PreparationProcedure` in the title instead of `sosa-oms:PreparationProcedure`.

See https://raw.githack.com/w3c/sdw-sosa-ssn/132-move-extra-oms-terms-into-sosa-core/ssn/index.html#OMSPreparationProcedure

**Review by ldesousa — APPROVED** [review]

**Pull request merged**
