### PR TITLE
Fix serialization inconsistencies between RDF/XML, N-Triples, and Turtle representations

### PR DESCRIPTION
**Pull request by white-gecko**
Remove superfluous carriage return chars (\r, &#xD;) from N-Triples and RDF/XML to be consistent with Turtle

### CODE REVIEW

**Comment by white-gecko** [comment]
This is my first shot, but there are also inconsistencies in:
- ssn/integrated/ssn.rdf ssn/integrated/ssn.ttl
- ssn/ssnx-dul/ssn-dul.rdf ssn/ssnx-dul/ssn-dul.ttl
- ssn/ssnx-dul/ssnx.rdf ssn/ssnx-dul/ssnx.ttl

**Comment by dr-shorthair** [comment]
Indeed. The alternative serializations are a long way behind. I will remove them now and they can be reinstated once the RDF implementation has stabilised.

**Comment by dr-shorthair** [comment]
Also note that the material in ssn-ext is in process of being integrated into the main SSN ontology.

**Comment by dr-shorthair** [comment]
Superseded by #181

**Pull request closed without merging**
