### PR TITLE
251 collections documentation

### LINKED ISSUE #251: Collections documentation
1. Generic Collections section needs to be brought up to date with addition of SamplingCollection and ExecutionCollection
2. Need to add in the examples of nested collections from SSN-ext

### PR DESCRIPTION
**Pull request by dr-shorthair**
Documentation had fallen behind recent addition of ExecutionCollection and SamplingCollection. 

See preview at https://raw.githack.com/w3c/sdw-sosa-ssn/251-collections-documentation/ssn/index.html#Collections 

Closes #251

### CODE REVIEW

**Comment by dr-shorthair** [comment]
This is a small tidy up of documentation, addressing things that got missed when we added `ExecutionCollection` and `SamplingCollection`. Can we get a couple of reviews so we can merge?

**Review by rob-metalinkage — APPROVED** [review]
I have approved - i feel slightly concerned by the phrase "the SSN ontology" used where generally its scope is SOSA - I always refer to the "SOSA ontology" since I never expect implementations to deal with OWL and the full SSN axiomitisation, so see SSN as the scope when its limited to SOSA really feels off.

**Comment by dr-shorthair** [comment]
@rob-metalinkage 
The document is very clear on this. The Ontology is called the SSN Ontology. SOSA is a _module_. 

See 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#abstract 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#Introduction
- https://w3c.github.io/sdw-sosa-ssn/ssn/#rdf-notation 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#Modularization 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#sosa-module 

and other places.

**Review by sgrellet — APPROVED** [review]
Juste one question (haven't opened the ttl though), why do we mention twice the hasMember (in red in the image below) ? it's already embarked via the specialization.
is that to ease readability ?

Otherwise LGTM

image

**Comment by dr-shorthair** [comment]
@sgrellet In the context of each specialised class, `hasMember` is further constrained to only have the more specialised range.

**Comment by sgrellet** [comment]
@dr-shorthair : sorry, I overlooked this. Thanks for the clarification

**Pull request merged**
