### PR TITLE
Remove `sosa:Host` retain `sosa:Platform`

### LINKED ISSUE #43: Should Observer and Host classes be equivalent to or superclass of Sensor and Platform?
In PR w3c/sdw#1402, `Observer` and `Host` are super classes of their `Sensor` and `Platform` counterparts. They are also kept more abstract because they are not sub-classes of `System`.

[Link to specific commit](https://github.com/w3c/sdw/pull/1402/commits/638f6c462d11d406c5a093cd0b0d522cc161231a)

Alternatively, we could have `Observer sameAs Sensor`, and `Host sameAs Platform`.

### LINKED ISSUE #56: What's the difference between Platform and Host?
What's the difference conceptually between Platform and Host? To my view, these are two labels for the same concept. I don't see the need for 2 separate concepts within SOSA.

Related to w3c/sdw-sosa-ssn#46

### PR DESCRIPTION
**Pull request by dr-shorthair**
Added note to explain that `sosa:Platform` is the SOSA implementation of OMS Host.

Closes #56

### CODE REVIEW

**Review by rob-metalinkage — APPROVED** [review]
I think this reflects the discussion and moves us forward to a review step.

**Comment by rob-metalinkage** [comment]
I did ask to see if @alexrobin could be added to the repository and review candidates.

**Review by sgrellet — COMMENTED** [review]
on ssn/integrated/sosa.ttl

line 202 "An environmental monitoring facility.". I wonder if that would make sense to refer to EU INSPIRE directive (2007/2/EC) theme 'Environmental Monitoring Facilities' (INSPIRE:EF) or create more confusion.
Indeed, the OMS:Host is modelled having in mind the work we did on INSPIRE:EF with @Kathi (and we should convince JRC to update that dataspecs)

line 338 sosa:Observer a rdfs:Class , owl:Class ;
will we discuss the sosa:Sensor VS OMS:Observer in another issue and PR ?

**Comment by alexrobin** [comment]
Thanks Simon. Looks good to me

**Comment by dr-shorthair** [comment]
@sgrellet asked
> line 338 sosa:Observer a rdfs:Class , owl:Class ;
will we discuss the sosa:Sensor VS OMS:Observer in another issue and PR ?

See #100

**Comment by dr-shorthair** [comment]
@sgrellet asked
> line 202 "An environmental monitoring facility.". I wonder if that would make sense to refer to EU INSPIRE directive (2007/2/EC) theme 'Environmental Monitoring Facilities' (INSPIRE:EF) or create more confusion.

If `sosa:Platform` is functionally equivalent to [EMF](https://inspire.ec.europa.eu/id/document/tg/ef) then that could be mentioned in the documentation or annotation. Perhaps this could be added as a `dcterms:source` reference? 

For the time being I have added a `skos:scopeNote`. 


Also see #57 for some ideas about how to document alignment to OMS.

**Review by sgrellet — APPROVED** [review]
> If sosa:Platform is functionally equivalent to [EMF](https://inspire.ec.europa.eu/id/document/tg/ef) then that could be mentioned in the documentation or annotation. Perhaps this could be added as a dcterms:source reference?

I'll add this as a dcterms:source. This will help using SOSA while maintaining compliancy with EU specs

**Pull request merged**
