### PR TITLE
Add rule for collection properties with multiple ranges

### LINKED ISSUE #141: Collection rule for property with multiple ranges
The consistency rule for properties whose value is a range needs to be extended to deal with the case where such a property is repeated - i.e. the collection has a property with multiple disjoint ranges. 
e.g. how to say that member observations of a collection where 

```
sosa:phenomenonTime _interval1_ , _interval2_ ; 
```

must have values that fall within one of the ranges.

### PR DESCRIPTION
**Pull request by dr-shorthair**
Fixes #141

### CODE REVIEW

**Comment by dr-shorthair** [comment]
@sgrellet does this work?
@avillar are these implementable?

**Comment by avillar** [comment]
> are these implementable?

In SHACL, most definitely, but I guess you're talking about OWL...

**Review by KathiSchleidt — APPROVED** [review]
Looks good!

**Review by hylkevds — APPROVED** [review]

**Review by sgrellet — APPROVED** [review]
fine with me as well

**Pull request merged**
