### PR TITLE
197 common modeling questions

### LINKED ISSUE #197: Common modeling questions
The section 'Common modeling questions' presents some examples of usage which give guidance as to how to apply SSN in applications. 
However, it is problematic in a number of ways:
1. in some cases (e.g. UoM) several options are presented without a strong recommendation as to which one is preferred for interoperability
2. the patterns are just given as examples, and are not formalized as profiles, potentially validatable
3. the set of patterns only covers a small part of the scope of potential variation in SSN usage

Since SSN is quite an abstract ontology, guidance on usage for applications is important. 
However, the scale and scope of the section in the current document is woefully inadequate. 

Propose to revise this section as follows: 
1. add commentary reflecting the notes above
2. OGC to develop a register of SSN Profiles targetted at various applications
3. reword the document to give stronger guidance and recommendations for some specific patterns.

### PR DESCRIPTION
**Pull request by dr-shorthair**
Streamlined Common Modeling Questions section with TTL and JSON-LD examples. 
The patterns for location and unit-of-measure are now more prescriptive. 

Preview here: https://raw.githack.com/w3c/sdw-sosa-ssn/197-common-modeling-questions/ssn/index.html#common-modeling-questions

### CODE REVIEW

**Comment by KathiSchleidt** [comment]
Are the `@` in the `hasSimpleResult `attributes correct in ssn/examples/2024ex-uomtype.jsonld?

```
    "hasSimpleResult": {
        "@type": "http://qudt.org/vocab/unit/DEG_C",
        "@value": "19.9"
    }
```

**Comment by hylkevds** [comment]
The thing that bothers me about this example is that the number is encoded as a String. Which means the reader can't be sure the writer used decimal point or comma...
Is there a way around this?

**Comment by KathiSchleidt** [comment]
In SOSA we only have phenomenonTime and resultTime, in OMS we also have validTime. Under [8.4 Forecasts](https://raw.githack.com/w3c/sdw-sosa-ssn/197-common-modeling-questions/ssn/index.html#forecasts) I read "A forecast may be represented as an observation where the value of sosa:phenomenonTime is later in time than the sosa:resultTime."

Do we leave this inconsistency, try to explain it, align it...?

**Comment by KathiSchleidt** [comment]
We need to clarify is sosa:System also gets a sosa:SystemOfInterest (parallel to sosa:Property and sosa:PropertyOfInterest), see #107 before we can finalize section [8.6 Generic or Specific Instances of sosa:System](https://raw.githack.com/w3c/sdw-sosa-ssn/197-common-modeling-questions/ssn/index.html#SOSASystem-instances)

Except for the bits listed here, looks good to go

**Comment by dr-shorthair** [comment]
> In SOSA we only have phenomenonTime and resultTime, in OMS we also have validTime. Under [8.4 Forecasts](https://raw.githack.com/w3c/sdw-sosa-ssn/197-common-modeling-questions/ssn/index.html#forecasts) I read "A forecast may be represented as an observation where the value of sosa:phenomenonTime is later in time than the sosa:resultTime."
> 
> Do we leave this inconsistency, try to explain it, align it...?

I don't see the inconsistency. `validTime` might be a useful addition, but the explanation of times for a forecast is correct with just "`sosa:phenomenonTime` is later than `sosa:resultTime`".

**Comment by dr-shorthair** [comment]
> The thing that bothers me about this example is that the number is encoded as a String. Which means the reader can't be sure the writer used decimal point or comma... Is there a way around this?

Yes, I believe that in RDF any literal that is not typed as a number is a string. 
If `http://qudt.org/vocab/unit/DEG_C` was asserted to be a sub-class of `xsd:decimal` then perhaps it would be OK? 

In the JSON encoding if the quotes are dropped from "19.9" does that make it a number?

**Comment by dr-shorthair** [comment]
> We need to clarify is sosa:System also gets a sosa:SystemOfInterest (parallel to sosa:Property and sosa:PropertyOfInterest), see #107 before we can finalize section [8.6 Generic or Specific Instances of sosa:System](https://raw.githack.com/w3c/sdw-sosa-ssn/197-common-modeling-questions/ssn/index.html#SOSASystem-instances)

The conversation seems to be converging. See #209

**Comment by hylkevds** [comment]
> In the JSON encoding if the quotes are dropped from "19.9" does that make it a number?

Yes, without the quotes it's a proper number.

**Review by oldskeptic — APPROVED** [review]

**Review by rob-metalinkage — APPROVED** [review]

**Pull request merged**
