### PR TITLE
Mirror ssn resources in sosa namespace

### LINKED ISSUE #48: Should we merge SSN and SOSA into a single namespace?
The idea would be to define all classes in SOSA, including Deployment, System, etc. that only exist in the SSN namespace as of today.

Even if we do that, we could keep the existing classes in the SSN namespace for backwards compatibility and just map them as equivalent to the new ones we add to SOSA namespace.

What do we do with constraints that are only defined in SSN in the current version?

### PR DESCRIPTION
**Pull request by dr-shorthair**
All the `ssn:` classes and properties are mirrored into the `sosa:` namespace but remain in the SSN graph. 
The existing `ssn:` resources have `owl:equivalentClass` or `owl:equivalentProperty` axioms to the new resources. 

Fixes #48

### CODE REVIEW

**Review by rob-metalinkage — DISMISSED** [review]
Refactor to remove commit removing inverseOf

**Review by rob-metalinkage — COMMENTED** [review]
Should sosa declare equivalence - or only ssn?  I guess a ssn+ sosa enclosure works and sosa alone needs to know nothing about ssn so this is safe and sensible,

**Comment by dr-shorthair** [comment]
> Refactor to remove commit removing inverseOf

The need for this `inverseOf` property depends somewhat on the final resolution of the `madeBySensor` vs `madeByObserver` issue. Are they `equivalentPropertys`? 

I will re-instate it for now, so we can move forward.

**Comment by dr-shorthair** [comment]
Hmm. If both `madeBySensor` and `madeByObserver` are `inverseOf` the same property, then I think this entails they are `equivalentProperty`.

**Comment by dr-shorthair** [comment]
> Should sosa declare equivalence - or only ssn? 

Unclear which resource should have the `owl:equivalentX` axiom attached. 
The original `ssn:` resource? The new `sosa:` resource? Both? 

For the time being they sit on the `sosa:` resource so the original resources are untouched internally.

**Comment by dr-shorthair** [comment]
Close and re-create as merge into `gh-pages`.

**Pull request closed without merging**
