### PR TITLE
107 move systemkind to system capabilities

### LINKED ISSUE #107: System types and individuals
It is still unclear when one wants to model a generic kind of system (aka, model, category, class, ...), whether they should model it as an instance of `ssn:System`, or a subclass of `ssn:System`.

As `ssn:System` is a superclass of `sosa:Sensor`, `sosa:Actuator`, `sosa:Sampler`, this confusion also applies to these class.

This ambiguity is reported in https://www.w3.org/TR/vocab-ssn/#SSNSystem-instances

In the SOSA/SSN examples, systems/sensors/actuators sometimes model generic sensor _kinds_, and sometimes a unique _actual instance_ of sensor:

- B.1 iPhone Barometer  describes `<sensor/35-207306-844818-0/BMP282>` as the _actual instance_ of a BMP282 high-precision barometric pressure sensor hosted on the iphone with IMEI 35-207306-844818-0.
- B.2 Coal Oil Point Reserve describes `<HUMICAP-H>` which is a _kind_ of Vaisala HUMICAP H-chip, a model of accurate temperature and relative humidity probe
- B.12 Examples from O&M refers to a a [graph corresponding to the OMXML examples](https://www.w3.org/TR/vocab-ssn/integrated/examples/om-20.ttl). Four sensors are referred to: `<http://www.csiro.au/people/ps205.html>`, `<http://www.example.org/register/process/scales34.xml>`, `<http://www.example.org/party/individual/abc123>`, `<urn:ogc:object:feature:Sensor:NASA:xyz345>`

It would help a lot to be able to identify _kinds_ of systems generically, the same way we do with property kinds. One advantage would be that we could reuse existing code lists, vocabularies, and taxonomies. Identifiers could be for example:
- Uniclass (ex: [Pr_75_50_76_88  Toxic and combustible gas detectors](https://uniclass.thenbs.com/taxon/pr_75_50_76_88))
- Harmonized Tariff Schedule (HTS) Code (ex: HTS Code: [9025.80.1000 for Electrical Hydrometers And Similar Floating Instruments, Thermometers, Pyrometers, Hygrometers And Psychrometers](https://www.datamyne.com/hts/90/9025801000))
- eClass
- Global Trade Item Numbers (GTINs) , Universal Product Codes (UPCs) , European Article Number (EAN),  etc.
    - see mapping to URNs: https://www.gs1.org/edi-xml/technical-user-guide/5_GS1_namespaces   
    - see RFC 5134  "A Uniform Resource Name Namespace for the EPCglobal Electronic Product Code (EPC) and Related Standards"
    - see GS1 Digital Link https://www.gs1.org/standards/gs1-digital-link
    - ex GTIN + Batch/lot (LGTIN) EPC URI  `urn:epc:class:lgtin:061414.0100000.987654321GFEDCBA`
    - ex Serialized GTIN (SGTIN) EPC Scheme `urn:epc:id:sgtin:061414.0100000.ABCDE12345`

Another advantage is that it would encourage manufacturers and vendors to define permanent URIs for their devices, and to expose structured data at the page that describes a device in a catalogue. Some examples of product IDs from manufacturer and vendor catalogues: 
- XMLD010B1S11 Pressure switch XMLD 10 bar - 2 stages fixed scale - 2 C/O https://tesensors.com/global/en/product/reference/XMLD010B1S11 
- BMP282 high-precision barometric pressure sensor https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/bmp280/
- Adafruit 5187 (STEMMA QT SCD-40 CO2 Humidity and Temperature sensor) on Digikey https://www.digikey.fr/fr/products/detail/adafruit-industries-llc/5187/15194668 
-  Adafruit 5187 (STEMMA QT SCD-40 CO2 Humidity and Temperature sensor) on mouser.fr https://www.mouser.fr/ProductDetail/Adafruit/5187

My proposal to **disambiguate the concept while maintaining backward compatibility with previous usages** would be to **split `ssn:System` in two classes**:

## `sosa:SystemOfInterest`

System is a unit of abstraction for real-world pieces of infrastructure that implement [Procedures](https://www.w3.org/TR/vocab-ssn/#SOSAProcedure). A System may have components, its subsystems, which are other Systems.

By the way, we should extend this definition to account for use cases when one wants to identify the digital twin of a system using that same class in SOSA (the digital model of a system of interest is also a system of interest).

## `sosa:SystemKind`

An instance of `sosa:SystemKind` describes a datasheet, vendor specification, or normative specification, of a sensor (in the sense of a prototypical description).

EXAMPLE: system with European Union energy label A++ , Energy Star labeled appliance,  BMP282, DHT22, Adafruit 5187, ... 

NOTE: Concepts from existing code lists, vocabularies, and taxonomies, may be used as instances of `sosa:SystemKind`.

NOTE: alternative names could be: `sosa:SystemModel`, `sosa:SystemType`, ...

### PR DESCRIPTION
**Pull request by dr-shorthair**
I've taken Alex's proposal and moved the classes, properties and related axioms into the System Capabilities extension module. 

Preview: https://raw.githack.com/w3c/sdw-sosa-ssn/107-move-systemkind-to-system-capabilities/ssn/index.html#System-capabilities

### CODE REVIEW

**Comment by alexrobin** [comment]
I'm fine with this but could we just use the `ssn` namespace (http://www.w3.org/ns/ssn/) for the capabilities module (instead of the old `ssn-system`,  http://www.w3.org/ns/ssn/systems) now that we moved pretty much everything else to `sosa`?

And deprecate concepts in `ssn-system` just like we did for the `ssn` concepts we moved to `sosa`?

**Comment by dr-shorthair** [comment]
@alexrobin interesting proposal. However, I'm not sure it works - 

We 'emptied out' the `ssn:` ns - the terms that were in there are now tagged 'deprecated'.   
The SSN module now only houses the axiomatization of the SOSA modules - as in the previous version. 

The plan is that dereferencing `http://www.w3.org/ns/ssn/` should get an ontology that supports everything that the previous edition did (the deprecated terms are still quietly imported), though it will also import additional terms in the `sosa:` ns. 

So I think it would be confusing to make `ssn:` do double duty, also housing the System Capabilities terms.

**Comment by dr-shorthair** [comment]
Closes #107

**Comment by dr-shorthair** [comment]
Update team agreed not to introduce a specific SystemKind class.

**Pull request closed without merging**
